auto_load_pipeline: true
default_cfg: 2.0
default_height: 512
default_noise_interpolation_strength: 0.99
default_img2img_strength: 0.6
default_max_new_tokens: 2048
default_negative: ' '
default_seed: 42
default_steps: 20
default_width: 512
enable_attention_slicing: false
enable_cpu_offload: false
enable_lora: true
enable_metadata_embed: true
enable_per_step_saving: false
add_positive_prompt_magic: true
enable_step_callback: false
enable_vae_tiling: true
gpu_text_encoder: 2:1.5GiB,3:16GiB
gpu_transformer: 0:13.5GiB,1:13.5GiB,2:16GiB
gpu_vae: cuda:2
local_files_only: true
lora_directory: ./loras
lora_max_count: 4
low_cpu_mem_usage: true
max_context_length: 32768
model_diffusion: ./models/Qwen-Image
model_scheduler: ./models/Qwen-Image/scheduler
model_text_encoder: ./models/Qwen2.5-VL-7B-Instruct-abliterated
model_tokenizer: ./models/Qwen-Image/tokenizer
model_vae: ./models/Qwen-Image/vae
num_workers: 1
output_directory: ./output
output_format: png
output_quality: 95
prompt_enhance_max_tokens: 1024
template_magic: ./templates/magic.txt
prompt_max_tokens: 1024
resolution_16_9: 1664,928
resolution_1_1: 1328,1328
resolution_3_4: 1140,1472
resolution_4_3: 1472,1140
resolution_9_16: 928,1664
resolution_multiple: 16
template_chat: ./templates/chat.txt
template_describe: ./templates/describe.txt
template_enhancement: ./templates/enhancement.txt
template_image: ./templates/image.txt
template_system: ./templates/system.txt
torch_dtype: bfloat16
ui_theme: light
